services:
  app:
    build: . 
    ports:
      - ${NODEuPORT}:3000
      - ${VITEuPORT}:5173
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev